version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_BACKEND_PORT:-4000}:4000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
    volumes:
      - ./backend:/app
      - /app/node_modules

networks:
  default:
    name: solana-ai-network
