apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
      exemplarTraceIdDestinations:
        - name: "trace_id"
          datasourceUid: "tempo"
      manageAlerts: true
      prometheusType: "Prometheus"
      prometheusVersion: "2.45.0"
      cacheLevel: "High"
      disableRecordingRules: false
      incrementalQueryOverlapWindow: "10m"
      exemplarEnabled: true
    secureJsonData: {}
    readOnly: false

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: loki
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    uid: tempo
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      httpMethod: "GET"
      serviceMap:
        datasourceUid: "prometheus"
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: "loki"
      tracesToLogs:
        datasourceUid: "loki"
        spanStartTimeShift: "1h"
        spanEndTimeShift: "-1h"
        filterByTraceID: true
        filterBySpanID: true
        tags: ["job", "instance", "pod", "namespace"]

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: "disable"
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: false
    editable: false

  - name: Redis
    type: redis-datasource
    url: redis://redis:6379
    editable: false
    jsonData:
      client: "standalone"
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0

  - name: Solana
    type: solana
    access: proxy
    url: ${SOLANA_RPC_URL}
    jsonData:
      commitment: "confirmed"
      httpMethod: "POST"
      wsEndpoint: ${SOLANA_WS_URL}
    editable: false
