name: Smart Contracts CI

on:
  push:
    paths:
      - 'contracts/**'
    branches: [ main, develop ]
  pull_request:
    paths:
      - 'contracts/**'
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.17.0/install)"
          export PATH="/github/home/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
      
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            contracts/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Run Tests
        run: |
          cd contracts
          cargo test --all
      
      - name: Build Programs
        run: |
          cd contracts
          cargo build-bpf
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: contract-builds
          path: contracts/target/deploy
          retention-days: 7

  security-audit:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Security audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
