name: Smart Contracts CI

on:
  push:
    paths:
      - 'contracts/**'
    branches: [ main, develop ]
  pull_request:
    paths:
      - 'contracts/**'
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run Tests
        run: cd contracts && cargo test
