name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
    branches: [ main, develop ]
  pull_request:
    paths:
      - 'frontend/**'
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: cd frontend && npm install
      - name: Run Tests
        run: cd frontend && npm test
      - name: Build
        run: cd frontend && npm run build
