# .github/workflows/frontend.yml
name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
    branches: [ main, develop ]
  pull_request:
    paths:
      - 'frontend/**'
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: cd frontend && npm install
      - name: Run Tests
        run: cd frontend && npm test
      - name: Build
        run: cd frontend && npm run build

# .github/workflows/backend.yml
name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main, develop ]
  pull_request:
    paths:
      - 'backend/**'
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: cd backend && npm install
      - name: Run Tests
        run: cd backend && npm test
      - name: Build
        run: cd backend && npm run build

# .github/workflows/contracts.yml
name: Smart Contracts CI

on:
  push:
    paths:
      - 'contracts/**'
    branches: [ main, develop ]
  pull_request:
    paths:
      - 'contracts/**'
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run Tests
        run: cd contracts && cargo test

# .github/ISSUE_TEMPLATE/bug_report.md
name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

# .github/ISSUE_TEMPLATE/feature_request.md
name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

# .github/PULL_REQUEST_TEMPLATE.md
## Description
Please include a summary of the changes and which issue is fixed.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
